# secrets
export ENV="dev"
export DEPLOYMENT_AWS_S3_BUCKET="aws-s3-bucket"
export PERSONAL_ACCESS_TOKEN="****"

# github actions
export CI="false"
#export HOME="-"
export GITHUB_WORKFLOW="-"
export GITHUB_RUN_ID="-"
export GITHUB_RUN_NUMBER="-"
export GITHUB_ACTION="-"
export GITHUB_ACTIONS="-"
export GITHUB_ACTOR="-"
export GITHUB_REPOSITORY="owner/repo"
export GITHUB_EVENT_NAME="-"
export GITHUB_EVENT_PATH="-"
export GITHUB_WORKSPACE="-"
export GITHUB_SHA="-"
export GITHUB_REF="-"
export GITHUB_HEAD_REF="-"
export GITHUB_BASE_REF="-"