AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket that helps managing deployments

Parameters:
  BucketName:
    Description: name of the bucket
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
    DeletionPolicy: Retain
