#https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

custom:
  projectID: servelerss-monorepo-101
  serviceID: demo-service

service:
  name: ${self:custom.projectID}--${self:custom.serviceID}

frameworkVersion: '>=1.0.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  stackName: ${self:service.name}--${self:provider.stage}
  apiName: ${self:service.name}--${self:provider.stage}
  memorySize: 128
  reservedConcurrency: 0
  timeout: 6
  logRetentionInDays: 1
  disableLogs: false
  deploymentBucket:
    name: ${env:INFRA_AWS_S3_BUCKET}
    maxPreviousDeploymentArtifacts: 4
  deploymentPrefix: serverless-deployments--${self:service.name}--${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"


package:
  exclude:
    - ./**
  include:
    - ./.bin/**

functions:
  echo:
    handler: .bin/echo
    events:
      - http:
          path: echo
          method: get
