name: Backend Deploy

on:
  repository_dispatch:
    types: [backend-deploy*]

jobs:
  deploy:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      INFRA_AWS_REGION: ${{secrets.INFRA_AWS_REGION}}
      INFRA_AWS_S3_BUCKET: ${{secrets.INFRA_AWS_S3_BUCKET}}
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '12'
#      - run: npm install -g serverless
      - run: curl -o- -L https://slss.io/install | bash
#      - run: BIN=../backend/deploy make compile-ci-deploy
#        working-directory: infra
      - run: ls -la ~/
      - run: ls -la /
      - run: ls -la
      - run: ls -la $HOME
      - run: echo $PATH
      - run: find / -name serverless
      - run: serverless --verion
#      - run: ./deploy
#        env:
#          ENV: ${{github.event.client_payload.env}}
#          SERVICE: ${{github.event.client_payload.service}}
#          CHECKSUM: ${{github.event.client_payload.checksum}}
