name: Backend Continuous Integration

on: push

jobs:

  test:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      # add new services bellow
      - run: make test -s -C demo-service

  build:
    needs: test
    if: github.ref == 'refs/heads/master'
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      INFRA_AWS_REGION: ${{secrets.INFRA_AWS_REGION}}
      INFRA_AWS_S3_BUCKET: ${{secrets.INFRA_AWS_S3_BUCKET}}
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      - run: go build -o ../backend/build internal/build/main.go
        working-directory: infra
      # add new services bellow
      - run: make compile -s -C demo-service
      - run: ./build --service=demo-service
