name: Backend Build

on:
  repository_dispatch:
    types: [backend-build*]

jobs:
  deploy:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      INFRA_AWS_REGION: ${{secrets.INFRA_AWS_REGION}}
      INFRA_AWS_S3_BUCKET: ${{secrets.INFRA_AWS_S3_BUCKET}}
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.client_payload.commitSHA}}
      - run: BIN=../backend/build make compile-ci-build
        working-directory: infra
      - run: make compile -s -C ${{github.event.client_payload.service}}
      - run: ./build
        env:
          SERVICE: ${{github.event.client_payload.service}}
