name: Backend Deploy

on:
  repository_dispatch:
    types: [backend-deploy*]

jobs:
  deploy:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      INFRA_AWS_REGION: ${{secrets.INFRA_AWS_REGION}}
      INFRA_AWS_S3_BUCKET: ${{secrets.INFRA_AWS_S3_BUCKET}}
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      - run: |
          mkdir -p $BINARIES_DIR
          curl -L -o $BINARY_PATH https://github.com/serverless/serverless/releases/download/$TAG/serverless-$PLATFORM-$ARCH
          chmod +x $BINARY_PATH
          echo "::add-path::$(readlink -f $BINARIES_DIR)"
        env:
          BINARIES_DIR: .serveless/bin
          BINARY_PATH: .serveless/bin/serverless
          PLATFORM: linux
          ARCH: x64
          TAG: v1.73.1
      - run: echo $PATH
      - run: serverless --version
      - run: BIN=../backend/deploy make compile-ci-deploy
        working-directory: infra
      - run: ./deploy
        env:
          ENV: ${{github.event.client_payload.env}}
          SERVICE: ${{github.event.client_payload.service}}
          CHECKSUM: ${{github.event.client_payload.checksum}}
