name: Continuous Deployment

on: repository_dispatch

# Alternative
# -----------
#on:
#  repository_dispatch:
#    types: [deploy demo-service, deploy demo-service2]
# -----------
# but for now will use the type mostly to display all the important info about the event
# this will help navigate the github actions list


jobs:
###  BACKEND DEPLOY  ###
  backend:
    if: github.event.client_payload.backend == 'true'
    runs-on: ubuntu-latest
    env:
      ENV: github.event.client_payload.env
      SERVICE: github.event.client_payload.service
    steps:
      - run: curl -o- -L https://slss.io/install | bash
      - run: echo "deploy demo-service"
