on: push
name: CI

jobs:

###  BACKEND TESTS  ###
  test-backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      # service tests
      - run: make -s -C demo-service

###  FRONTEND TESTS  ###
  test-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run lint

###  BACKEND BUILDS  ###
  build-backend:
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      - run: echo "go run internal/deployment/main.go"
