name: Example

on:
  repository_dispatch:
    types: [example*]

jobs:
  play-time:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_RUN_ID
      - run: echo $GITHUB_EVENT_NAME
      - run: cat $GITHUB_EVENT_PATH
