name: Frontend Test

on:
  push:
    paths:
      - '.force'
      - 'frontend/**'
      - '.github/workflows/frontend**'


jobs:

  test:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
