name: Infra

on:
  push:
    branches:
      - master
    paths:
      - '.force'
      - 'infra/**'
      - '.github/workflows/infra**'

jobs:
  sync:
    defaults:
      run:
        working-directory: infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - run: make test-compile
      - run: make deploy
        env:
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          INFRA_AWS_S3_BUCKET: ${{secrets.INFRA_AWS_S3_BUCKET}}
